### ISSUE TITLE
Strange results from disassemble for fib

### ISSUE THREAD

**Issue by pmatos** [samth/disassemble#10]
With racket 7.0, disassemble for fib:
```
(define (fib n)
  (cond
    [(<= n 1) n]
    [else (fib (+ n 1) (+ n 2))]))
```

returns the following partial assembly code:
```
      2f: 48bed749bc2e567f0000           (mov rsi #x7f562ebc49d7)
      39: 488975d8                       (mov (mem64+ rbp #x-28) rsi)
      3d: 48bee049bc2e567f0000           (mov rsi #x7f562ebc49e0)
```

With nasm it shows up as:
```
0000002F  48BE574EBC2E567F  mov rsi,0x7f562ebc4e57
         -0000
00000039  488975D8          mov [rbp-0x28],rsi
0000003D  48BE604EBC2E567F  mov rsi,0x7f562ebc4e60
         -0000
```

I am confused about what those `-0000` are and they look like some parsing bug of sorts.

**Comment by pmatos** [comment]
Also, I just noticed that the constants are also slightly different with and without nasm. This might be yet another issue.

**Comment by mflatt** [comment]
The "-0000" is nasm breaking the bytes of a long instruction across multiple lines.

I think you're seeing the constant change after restarting Racket. It's the address of a static variable in the runtime system, and ASLR changes the address each time.
